# Generated by Django 4.1.5 on 2023-05-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_customerdata_user'),
    ]

    operations = [

    ]
